// Generated by tools/build.py from scriptlets/src. Do not edit.
(() => {
// Shared helpers for scriptlets. All source files are concatenated into one
// IIFE (scriptlets/runtime.js) that runs in the page's MAIN world at document_start.

const SCRIPTLETS = Object.create(null);
const ABORT_MAGIC = "AdWall" + Math.random().toString(36).slice(2);

const natives = {
  defineProperty: Object.defineProperty,
  getOwnPropertyDescriptor: Object.getOwnPropertyDescriptor,
  fnToString: Function.prototype.toString,
  JSONparse: JSON.parse,
  JSONstringify: JSON.stringify,
  fetch: self.fetch,
  setTimeout: self.setTimeout,
  setInterval: self.setInterval,
};

// "/regex/flags" -> RegExp, "" -> match everything, otherwise literal substring.
function patternToRegex(pattern, flags = "") {
  if (pattern === undefined || pattern === "" || pattern === "*") return /^/;
  const m = /^\/(.+)\/([gimsuy]*)$/.exec(pattern);
  if (m) {
    try { return new RegExp(m[1], m[2] || flags); } catch { return /(?!)/; }
  }
  return new RegExp(pattern.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), flags);
}

// uBO needles may be negated with a leading "!".
function needleMatcher(needle) {
  let negate = false;
  if (typeof needle === "string" && needle.startsWith("!")) {
    negate = true;
    needle = needle.slice(1);
  }
  const re = patternToRegex(needle);
  return (text) => re.test(String(text)) !== negate;
}

function fnText(fn) {
  try { return typeof fn === "function" ? natives.fnToString.call(fn) : String(fn); } catch { return ""; }
}

// Make a replacement function look native to anti-adblock toString() checks.
function disguise(fake, real) {
  try {
    natives.defineProperty(fake, "toString", { value: () => natives.fnToString.call(real), configurable: true, writable: true });
    natives.defineProperty(fake, "name", { value: real.name, configurable: true });
  } catch {}
  return fake;
}

function throwAbort() {
  throw new ReferenceError(ABORT_MAGIC);
}

// Swallow our own abort errors so they don't show up as page errors.
self.addEventListener("error", (e) => {
  if (String(e.message || e.error?.message).includes(ABORT_MAGIC)) e.preventDefault();
}, true);

const noopFunc = function () {};
const CONSTANTS = {
  undefined: undefined, false: false, true: true, null: null, "''": "", "": "",
  noopFunc, trueFunc: () => true, falseFunc: () => false, throwFunc: throwAbort,
  emptyObj: {}, emptyArr: [], "{}": {}, "[]": [], emptyStr: "", noopCallbackFunc: () => noopFunc,
  "-1": -1, yes: "yes", no: "no", on: "on", off: "off", accept: "accept", reject: "reject",
};

// Returns [ok, value]. Only a safe set of values is allowed for untrusted lists.
function constantValue(raw) {
  if (Object.prototype.hasOwnProperty.call(CONSTANTS, raw)) {
    const v = CONSTANTS[raw];
    return [true, v instanceof Object && typeof v !== "function" ? (Array.isArray(v) ? [] : {}) : v];
  }
  if (/^-?\d+$/.test(raw) && Math.abs(Number(raw)) <= 0x7fff) return [true, Number(raw)];
  return [false];
}

// Walks "a.b.c" on window. Calls onFinal(owner, prop) when the owner of the last
// property exists, installing setters along the way so later assignments are caught.
function trapChain(chain, onFinal, root = self) {
  const trap = (owner, parts) => {
    const prop = parts[0];
    if (parts.length === 1) {
      onFinal(owner, prop);
      return;
    }
    let current = owner[prop];
    if (current instanceof Object) {
      trap(current, parts.slice(1));
      return;
    }
    const desc = natives.getOwnPropertyDescriptor(owner, prop);
    if (desc && desc.configurable === false) return;
    try {
      natives.defineProperty(owner, prop, {
        configurable: true,
        get: () => current,
        set: (v) => {
          current = v;
          if (v instanceof Object) trap(v, parts.slice(1));
        },
      });
    } catch {}
  };
  trap(root, chain.split("."));
}

// "url:/ads/ method:POST" style property matching used by fetch/xhr scriptlets.
function parsePropsToMatch(raw) {
  const props = new Map();
  if (!raw || raw === "*") return props;
  for (const token of raw.split(/\s+/)) {
    const i = token.indexOf(":");
    if (i === -1 || /^https?$/.test(token.slice(0, i))) props.set("url", needleMatcher(token));
    else props.set(token.slice(0, i), needleMatcher(token.slice(i + 1)));
  }
  return props;
}

function propsMatch(props, details) {
  for (const [key, test] of props) {
    if (!test(details[key] ?? "")) return false;
  }
  return true;
}

function requestDetails(resource, init) {
  const details = {};
  if (resource instanceof Request) {
    for (const k of ["url", "method", "mode", "credentials", "referrer", "body"]) details[k] = resource[k];
  } else {
    details.url = String(resource);
  }
  if (init && typeof init === "object") {
    for (const k of Object.keys(init)) details[k] = typeof init[k] === "string" ? init[k] : "";
  }
  return details;
}

// Run callback now and on every DOM change until the page is done (or forever).
function onDomChange(callback, stopAfterLoad = false) {
  const run = () => { try { callback(); } catch {} };
  let pending = false;
  const observer = new MutationObserver(() => {
    if (pending) return;
    pending = true;
    natives.setTimeout.call(self, () => { pending = false; run(); }, 0);
  });
  const start = () => {
    run();
    observer.observe(document, { childList: true, subtree: true, attributes: true });
  };
  if (document.documentElement) start();
  else natives.setTimeout.call(self, start, 0);
  if (stopAfterLoad) self.addEventListener("load", () => natives.setTimeout.call(self, () => observer.disconnect(), 2000));
}

// Scriptlets that trap global properties.

// set / set-constant: force window.a.b.c to a constant value.
SCRIPTLETS["set"] = (chain, raw, ...extra) => {
  if (!chain) return;
  const [ok, value] = constantValue(raw);
  if (!ok) return;
  applyConstant(chain, value, extra);
};

// trusted-set: arbitrary JSON value, only emitted from trusted lists.
SCRIPTLETS["trusted-set"] = (chain, raw) => {
  if (!chain) return;
  let value;
  try {
    const parsed = natives.JSONparse(raw);
    value = parsed && typeof parsed === "object" && "value" in parsed ? parsed.value : parsed;
  } catch {
    const [ok, v] = constantValue(raw);
    if (!ok) return;
    value = v;
  }
  applyConstant(chain, value, []);
};

function applyConstant(chain, value, extra) {
  const asCallback = extra.includes("asCallback");
  const final = asCallback ? () => value : value;
  trapChain(chain, (owner, prop) => {
    const desc = natives.getOwnPropertyDescriptor(owner, prop);
    if (desc && desc.configurable === false) {
      try { owner[prop] = final; } catch {}
      return;
    }
    try {
      natives.defineProperty(owner, prop, {
        configurable: true,
        enumerable: desc ? desc.enumerable : true,
        get: () => final,
        set: () => {},
      });
    } catch {}
  });
}

// aopr / abort-on-property-read
SCRIPTLETS["aopr"] = (chain) => {
  if (!chain) return;
  trapChain(chain, (owner, prop) => {
    try { natives.defineProperty(owner, prop, { configurable: true, get: throwAbort, set() {} }); } catch {}
  });
};

// aopw / abort-on-property-write
SCRIPTLETS["aopw"] = (chain) => {
  if (!chain) return;
  trapChain(chain, (owner, prop) => {
    try {
      const desc = natives.getOwnPropertyDescriptor(owner, prop);
      if (desc && desc.configurable === false) return;
      natives.defineProperty(owner, prop, { configurable: true, set: throwAbort });
    } catch {}
  });
};

// acs / abort-current-script: abort when a script whose text or src matches
// the needle touches the property.
SCRIPTLETS["acs"] = (chain, needle = "", context = "") => {
  if (!chain) return;
  const matches = needleMatcher(needle);
  const contextMatches = needleMatcher(context);
  const scriptText = () => {
    const s = document.currentScript;
    if (!(s instanceof HTMLScriptElement)) return null;
    return s.src ? s.src : s.textContent;
  };
  const check = () => {
    const text = scriptText();
    if (text !== null && matches(text) && contextMatches(text)) throwAbort();
  };
  trapChain(chain, (owner, prop) => {
    const desc = natives.getOwnPropertyDescriptor(owner, prop);
    if (desc && desc.configurable === false) return;
    let value = owner[prop];
    const getter = desc?.get;
    const setter = desc?.set;
    try {
      natives.defineProperty(owner, prop, {
        configurable: true,
        get() { check(); return getter ? getter.call(this) : value; },
        set(v) { check(); if (setter) setter.call(this, v); else value = v; },
      });
    } catch {}
  });
};

// aost / abort-on-stack-trace
SCRIPTLETS["aost"] = (chain, needle = "") => {
  if (!chain) return;
  const matches = needleMatcher(needle);
  const check = () => {
    if (matches(new Error().stack || "")) throwAbort();
  };
  trapChain(chain, (owner, prop) => {
    const desc = natives.getOwnPropertyDescriptor(owner, prop);
    if (desc && desc.configurable === false) return;
    let value = owner[prop];
    try {
      natives.defineProperty(owner, prop, {
        configurable: true,
        get() { check(); return desc?.get ? desc.get.call(this) : value; },
        set(v) { check(); if (desc?.set) desc.set.call(this, v); else value = v; },
      });
    } catch {}
  });
};

// nofab / fuckadblock defuser: fake detector libraries that never detect.
SCRIPTLETS["nofab"] = () => {
  const Fake = function () {};
  Fake.prototype = {
    check() { return false; }, clearEvent() {}, emitEvent() {},
    on(detected, cb) { if (!detected && typeof cb === "function") natives.setTimeout.call(self, cb, 1); return this; },
    onDetected() { return this; },
    onNotDetected(cb) { if (typeof cb === "function") natives.setTimeout.call(self, cb, 1); return this; },
    setOption() { return this; },
    options: { set() { return this; }, get() { return this; } },
  };
  const instance = new Fake();
  for (const name of ["FuckAdBlock", "BlockAdBlock", "SniffAdBlock"]) {
    try { natives.defineProperty(self, name, { value: Fake, configurable: true }); } catch {}
  }
  for (const name of ["fuckAdBlock", "blockAdBlock", "sniffAdBlock"]) {
    try { natives.defineProperty(self, name, { value: instance, configurable: true }); } catch {}
  }
};

// popads-dummy: satisfy PopAds checks without loading anything.
SCRIPTLETS["popads-dummy"] = () => {
  try {
    natives.defineProperty(self, "PopAds", { value: {}, configurable: true });
    natives.defineProperty(self, "popns", { value: {}, configurable: true });
  } catch {}
};

// Scriptlets that neutralize timers, eval, event listeners and popups.

function wrapTimer(name, shouldBlock, adjustDelay) {
  const real = self[name];
  const fake = disguise(function (callback, delay, ...rest) {
    const text = fnText(callback);
    if (shouldBlock && shouldBlock(text, delay)) callback = noopFunc;
    if (adjustDelay) delay = adjustDelay(text, delay);
    return real.call(this, callback, delay, ...rest);
  }, real);
  self[name] = fake;
}

function delayMatcher(raw) {
  if (raw === undefined || raw === "" || raw === "*") return () => true;
  const negate = raw.startsWith("!");
  const n = Number(negate ? raw.slice(1) : raw);
  return (delay) => (Number(delay) === n) !== negate;
}

// nostif / no-setTimeout-if, nosiif / no-setInterval-if
for (const [scriptlet, timer] of [["nostif", "setTimeout"], ["nosiif", "setInterval"]]) {
  SCRIPTLETS[scriptlet] = (needle = "", delay) => {
    const matches = needleMatcher(needle);
    const delayOk = delayMatcher(delay);
    wrapTimer(timer, (text, d) => matches(text) && delayOk(d));
  };
}

// nano-stb / adjust-setTimeout, nano-sib / adjust-setInterval: speed up countdowns.
for (const [scriptlet, timer] of [["nano-stb", "setTimeout"], ["nano-sib", "setInterval"]]) {
  SCRIPTLETS[scriptlet] = (needle = "", delay = "1000", boost = "0.05") => {
    const matches = needleMatcher(needle);
    const target = delay === "*" ? null : Number(delay);
    let factor = Number(boost);
    if (!Number.isFinite(factor)) factor = 0.05;
    factor = Math.min(50, Math.max(0.001, factor));
    wrapTimer(timer, null, (text, d) => (matches(text) && (target === null || Number(d) === target) ? d * factor : d));
  };
}

// noeval-if / prevent-eval-if, noeval
SCRIPTLETS["noeval-if"] = (needle = "") => {
  const matches = needleMatcher(needle);
  const real = self.eval;
  self.eval = disguise(function (code) {
    if (matches(String(code))) return undefined;
    return real.call(self, code);
  }, real);
};
SCRIPTLETS["noeval"] = () => SCRIPTLETS["noeval-if"]("");

// aeld / prevent-addEventListener
SCRIPTLETS["aeld"] = (type = "", needle = "") => {
  const typeMatches = needleMatcher(type);
  const handlerMatches = needleMatcher(needle);
  const proto = EventTarget.prototype;
  const real = proto.addEventListener;
  proto.addEventListener = disguise(function (evType, handler, ...rest) {
    let text = "";
    try {
      text = typeof handler === "function" ? fnText(handler) : fnText(handler?.handleEvent);
    } catch {}
    if (typeMatches(evType) && handlerMatches(text)) return undefined;
    return real.call(this, evType, handler, ...rest);
  }, real);
};

// nowoif / no-window-open-if: refuse popups, returning a harmless fake window.
SCRIPTLETS["nowoif"] = (needle = "") => {
  const matches = needleMatcher(needle);
  const real = self.open;
  const fakeWindow = () => {
    const w = { closed: false, opener: self, location: { href: "" }, document: { write() {}, close() {} } };
    w.close = () => { w.closed = true; };
    w.focus = w.blur = w.postMessage = noopFunc;
    w.window = w.self = w;
    return w;
  };
  self.open = disguise(function (url, ...rest) {
    if (matches(url === undefined ? "" : String(url))) return fakeWindow();
    return real.call(this, url, ...rest);
  }, real);
};

// nowebrtc: WebRTC is abused to route ads around blockers.
SCRIPTLETS["nowebrtc"] = () => {
  for (const name of ["RTCPeerConnection", "webkitRTCPeerConnection"]) {
    const real = self[name];
    if (typeof real !== "function") continue;
    const Fake = function () {
      return {
        close: noopFunc, createDataChannel: noopFunc, addEventListener: noopFunc, removeEventListener: noopFunc,
        createOffer: () => Promise.reject(new DOMException("", "NotAllowedError")),
        setLocalDescription: () => Promise.resolve(), setRemoteDescription: () => Promise.resolve(),
      };
    };
    self[name] = disguise(Fake, real);
  }
};

// refresh-defuser: stop <meta http-equiv=refresh> redirects to ad pages.
SCRIPTLETS["refresh-defuser"] = () => {
  const run = () => {
    for (const meta of document.querySelectorAll('meta[http-equiv="refresh" i]')) meta.remove();
  };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", run, { once: true });
  else run();
};

// Scriptlets that edit the DOM: inline script text, attributes, classes, links.

function watchNodes(nodeName, onNode) {
  const nameMatches = needleMatcher(nodeName);
  const visit = (node) => {
    if (node.nodeType === 1 && nameMatches(node.nodeName.toLowerCase())) onNode(node);
    else if (node.nodeType === 3 && nameMatches("#text")) onNode(node);
  };
  const observer = new MutationObserver((mutations) => {
    for (const m of mutations) for (const n of m.addedNodes) visit(n);
  });
  // Parser-inserted scripts run after a microtask checkpoint, so this
  // observer sees (and can empty) inline scripts before they execute.
  const start = () => observer.observe(document, { childList: true, subtree: true });
  if (document.documentElement) start();
  else natives.setTimeout.call(self, start, 0);
  if (document.documentElement) {
    for (const n of document.querySelectorAll(nodeName.startsWith("/") ? "*" : nodeName || "*")) visit(n);
  }
}

// rmnt / remove-node-text
SCRIPTLETS["rmnt"] = (nodeName = "", needle = "") => {
  if (!nodeName) return;
  const matches = needleMatcher(needle);
  watchNodes(nodeName, (node) => {
    if (matches(node.textContent)) node.textContent = "";
  });
};

// rpnt / replace-node-text (and trusted-rpnt)
SCRIPTLETS["rpnt"] = (nodeName = "", pattern = "", replacement = "", ...extra) => {
  if (!nodeName || !pattern) return;
  const re = patternToRegex(pattern, "g");
  const conditionIndex = extra.indexOf("condition");
  const condition = conditionIndex !== -1 ? needleMatcher(extra[conditionIndex + 1]) : () => true;
  watchNodes(nodeName, (node) => {
    const text = node.textContent;
    if (!condition(text)) return;
    const replaced = text.replace(re, replacement);
    if (replaced !== text) node.textContent = replaced;
  });
};

function parseBehavior(raw) {
  return { stay: /stay/.test(raw || ""), complete: /complete/.test(raw || "") };
}

// ra / remove-attr
SCRIPTLETS["ra"] = (attrs = "", selector = "", behavior = "") => {
  const names = attrs.split(/\s*\|\s*/).filter(Boolean);
  if (!names.length) return;
  const sel = selector || names.map((a) => `[${CSS.escape(a)}]`).join(",");
  const { stay, complete } = parseBehavior(behavior);
  const run = () => {
    for (const el of document.querySelectorAll(sel)) for (const a of names) el.removeAttribute(a);
  };
  const go = () => (stay ? onDomChange(run) : onDomChange(run, true));
  if (complete && document.readyState !== "complete") self.addEventListener("load", go, { once: true });
  else go();
};

// rc / remove-class
SCRIPTLETS["rc"] = (classes = "", selector = "", behavior = "") => {
  const names = classes.split(/\s*\|\s*/).filter(Boolean);
  if (!names.length) return;
  const sel = selector || names.map((c) => `.${CSS.escape(c)}`).join(",");
  const { stay, complete } = parseBehavior(behavior);
  const run = () => {
    for (const el of document.querySelectorAll(sel)) el.classList.remove(...names);
  };
  const go = () => (stay ? onDomChange(run) : onDomChange(run, true));
  if (complete && document.readyState !== "complete") self.addEventListener("load", go, { once: true });
  else go();
};

// href-sanitizer: replace tracking/ad redirect links with their real destination.
SCRIPTLETS["href-sanitizer"] = (selector = "", source = "text") => {
  if (!selector) return;
  const extract = (a) => {
    if (source === "text") return a.textContent.trim();
    if (source.startsWith("?")) {
      try { return new URL(a.href, location.href).searchParams.get(source.slice(1)) || ""; } catch { return ""; }
    }
    if (source.startsWith("[") && source.endsWith("]")) return a.getAttribute(source.slice(1, -1)) || "";
    return "";
  };
  onDomChange(() => {
    for (const a of document.querySelectorAll(selector)) {
      const target = extract(a);
      if (!/^https?:\/\//.test(target)) continue;
      try { new URL(target); } catch { continue; }
      if (a.href !== target) a.setAttribute("href", target);
    }
  });
};

// Scriptlets that edit JSON and network responses (this is what strips YouTube ads).

// Path syntax: "a.b.c", "[]" = every key, "[-]" = remove array elements that contain the rest.
function prunePath(obj, parts, dryRun) {
  if (obj === null || typeof obj !== "object") return false;
  const [head, ...rest] = parts;
  if (head === "[]") {
    let found = false;
    for (const key of Object.keys(obj)) found = prunePath(obj[key], rest, dryRun) || found;
    return found;
  }
  if (head === "[-]") {
    if (!Array.isArray(obj)) return false;
    let found = false;
    for (let i = obj.length - 1; i >= 0; i--) {
      if (rest.length === 0 || prunePath(obj[i], rest, true)) {
        found = true;
        if (!dryRun) obj.splice(i, 1);
      }
    }
    return found;
  }
  if (!(head in obj)) return false;
  if (rest.length === 0) {
    if (!dryRun) delete obj[head];
    return true;
  }
  return prunePath(obj[head], rest, dryRun);
}

function makePruner(rawPrunePaths = "", rawNeedlePaths = "") {
  const split = (raw) => raw.split(/\s+/).filter((p) => p && p !== "important").map((p) => p.split("."));
  const prune = split(rawPrunePaths);
  const needles = split(rawNeedlePaths);
  return (obj) => {
    if (obj === null || typeof obj !== "object" || !prune.length) return obj;
    if (needles.length && !needles.every((n) => prunePath(obj, n, true))) return obj;
    for (const p of prune) prunePath(obj, p, false);
    return obj;
  };
}

function extraArgs(extra) {
  const map = {};
  for (let i = 0; i + 1 < extra.length; i += 2) map[extra[i]] = extra[i + 1];
  return map;
}

function rebuildResponse(original, body) {
  const r = new Response(body, { status: original.status, statusText: original.statusText, headers: original.headers });
  for (const key of ["url", "type", "redirected"]) {
    try { natives.defineProperty(r, key, { value: original[key] }); } catch {}
  }
  return r;
}

// Wrap fetch so matching responses get their text transformed.
function hookFetchResponse(props, transformText) {
  const real = self.fetch;
  self.fetch = disguise(function (resource, init) {
    const promise = real.apply(this, arguments);
    if (!propsMatch(props, requestDetails(resource, init))) return promise;
    return promise.then((resp) =>
      resp.clone().text().then((text) => {
        const out = transformText(text);
        return out === text ? resp : rebuildResponse(resp, out);
      }).catch(() => resp)
    );
  }, real);
}

// --- XHR hooking (installed once, shared by all XHR scriptlets) ---------------
const xhrInfo = new WeakMap();
const xhrTransforms = [];
const xhrBlocks = [];
let xhrInstalled = false;

function installXhr() {
  if (xhrInstalled) return;
  xhrInstalled = true;
  const proto = XMLHttpRequest.prototype;
  const open = proto.open;
  const send = proto.send;

  proto.open = disguise(function (method, url, ...rest) {
    xhrInfo.set(this, { details: { method: String(method), url: String(url) } });
    return open.call(this, method, url, ...rest);
  }, open);

  proto.send = disguise(function (body) {
    const info = xhrInfo.get(this);
    if (info) {
      const block = xhrBlocks.find((b) => propsMatch(b.props, info.details));
      if (block) {
        fakeXhr(this, info, block.body);
        return undefined;
      }
      info.transforms = xhrTransforms.filter((t) => propsMatch(t.props, info.details));
    }
    return send.call(this, body);
  }, send);

  for (const prop of ["response", "responseText"]) {
    const desc = natives.getOwnPropertyDescriptor(proto, prop);
    if (!desc?.get) continue;
    natives.defineProperty(proto, prop, {
      configurable: true,
      enumerable: desc.enumerable,
      get() {
        const info = xhrInfo.get(this);
        if (info?.fake !== undefined) return info.fake;
        const value = desc.get.call(this);
        if (!info?.transforms?.length || this.readyState !== 4) return value;
        if (info.cached === undefined) {
          let text = null;
          if (this.responseType === "" || this.responseType === "text") text = desc.get.call(this);
          else if (this.responseType === "json") text = natives.JSONstringify(value);
          if (text === null) return value;
          for (const t of info.transforms) text = t.transform(text);
          info.cached = text;
        }
        return this.responseType === "json" ? natives.JSONparse(info.cached) : info.cached;
      },
    });
  }
}

function fakeXhr(xhr, info, body) {
  info.fake = body;
  const define = (k, v) => { try { natives.defineProperty(xhr, k, { value: v, configurable: true }); } catch {} };
  define("readyState", 4);
  define("status", 200);
  define("statusText", "OK");
  define("responseURL", info.details.url);
  natives.setTimeout.call(self, () => {
    for (const type of ["readystatechange", "load", "loadend"]) xhr.dispatchEvent(new Event(type));
  }, 1);
}

function textPruner(pruner) {
  return (text) => {
    let obj;
    try { obj = natives.JSONparse(text); } catch { return text; }
    const before = natives.JSONstringify(obj);
    const after = natives.JSONstringify(pruner(obj));
    return after === before ? text : after;
  };
}

function fakeBody(raw) {
  if (raw === "emptyObj" || raw === "{}") return "{}";
  if (raw === "emptyArr" || raw === "[]") return "[]";
  return "";
}

// json-prune: prune objects produced by JSON.parse and Response.json().
SCRIPTLETS["json-prune"] = (rawPrunePaths, rawNeedlePaths) => {
  const pruner = makePruner(rawPrunePaths, rawNeedlePaths);
  const realParse = JSON.parse;
  JSON.parse = disguise(function () {
    return pruner(realParse.apply(this, arguments));
  }, realParse);
  const realJson = Response.prototype.json;
  Response.prototype.json = disguise(function () {
    return realJson.apply(this, arguments).then(pruner);
  }, realJson);
};

SCRIPTLETS["json-prune-fetch-response"] = (rawPrunePaths, rawNeedlePaths, ...extra) => {
  const props = parsePropsToMatch(extraArgs(extra).propsToMatch);
  hookFetchResponse(props, textPruner(makePruner(rawPrunePaths, rawNeedlePaths)));
};

SCRIPTLETS["json-prune-xhr-response"] = (rawPrunePaths, rawNeedlePaths, ...extra) => {
  installXhr();
  const props = parsePropsToMatch(extraArgs(extra).propsToMatch);
  xhrTransforms.push({ props, transform: textPruner(makePruner(rawPrunePaths, rawNeedlePaths)) });
};

SCRIPTLETS["trusted-replace-fetch-response"] = (pattern = "", replacement = "", propsToMatch = "") => {
  if (!pattern) return;
  const re = patternToRegex(pattern, "g");
  hookFetchResponse(parsePropsToMatch(propsToMatch), (text) => text.replace(re, replacement));
};

SCRIPTLETS["trusted-replace-xhr-response"] = (pattern = "", replacement = "", propsToMatch = "") => {
  if (!pattern) return;
  installXhr();
  const re = patternToRegex(pattern, "g");
  xhrTransforms.push({ props: parsePropsToMatch(propsToMatch), transform: (text) => text.replace(re, replacement) });
};

// no-fetch-if / prevent-fetch: answer matching requests with an empty response.
SCRIPTLETS["no-fetch-if"] = (propsToMatch = "", responseBody = "") => {
  if (!propsToMatch) return;
  const props = parsePropsToMatch(propsToMatch);
  const real = self.fetch;
  self.fetch = disguise(function (resource, init) {
    const details = requestDetails(resource, init);
    if (!propsMatch(props, details)) return real.apply(this, arguments);
    const resp = new Response(fakeBody(responseBody), { status: 200, statusText: "OK" });
    try { natives.defineProperty(resp, "url", { value: details.url }); } catch {}
    return Promise.resolve(resp);
  }, real);
};

// no-xhr-if / prevent-xhr
SCRIPTLETS["no-xhr-if"] = (propsToMatch = "", directive = "") => {
  if (!propsToMatch) return;
  installXhr();
  xhrBlocks.push({ props: parsePropsToMatch(propsToMatch), body: fakeBody(directive) });
};

// Scriptlets that set or remove cookies and web storage (e.g. "ad blocker notice dismissed").

const SAFE_STORAGE_VALUES = /^(undefined|null|false|true|yes|no|on|off|accept|accepted|reject|rejected|allow|allowed|deny|denied|ok|\{\}|\[\]|""|''|-?\d+|\$remove\$|emptyObj|emptyArr|emptyStr)$/;

function storageValue(raw) {
  if (raw === "emptyObj") return "{}";
  if (raw === "emptyArr") return "[]";
  if (raw === "emptyStr" || raw === '""' || raw === "''") return "";
  return raw;
}

function setStorageItem(storageName, key, raw, trusted) {
  if (!key || (!trusted && !SAFE_STORAGE_VALUES.test(raw))) return;
  try {
    const storage = self[storageName];
    if (raw === "$remove$") {
      const matches = needleMatcher(key);
      for (const k of Object.keys(storage)) if (k === key || (key.startsWith("/") && matches(k))) storage.removeItem(k);
    } else {
      storage.setItem(key, storageValue(raw));
    }
  } catch {}
}

SCRIPTLETS["set-local-storage-item"] = (key, value) => setStorageItem("localStorage", key, value, false);
SCRIPTLETS["set-session-storage-item"] = (key, value) => setStorageItem("sessionStorage", key, value, false);
SCRIPTLETS["trusted-set-local-storage-item"] = (key, value) => setStorageItem("localStorage", key, value, true);

function writeCookie(name, value, path) {
  const cookiePath = path === "none" ? "" : `; path=${path === "" || path === undefined ? "/" : path}`;
  try { document.cookie = `${encodeURIComponent(name)}=${encodeURIComponent(value)}${cookiePath}`; } catch {}
}

SCRIPTLETS["set-cookie"] = (name, value = "", path) => {
  if (!name || !SAFE_STORAGE_VALUES.test(value)) return;
  writeCookie(name, storageValue(value), path);
};

SCRIPTLETS["trusted-set-cookie"] = (name, value = "", _offset, _reload, path) => {
  if (!name) return;
  writeCookie(name, value.replace("$now$", String(Date.now())), path);
};

// remove-cookie / cookie-remover
SCRIPTLETS["remove-cookie"] = (needle = "") => {
  const matches = needleMatcher(needle);
  const remove = () => {
    for (const part of document.cookie.split(";")) {
      const name = part.split("=")[0].trim();
      if (!name || !matches(name)) continue;
      const expire = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 GMT`;
      const domains = ["", location.hostname, "." + location.hostname.split(".").slice(-2).join(".")];
      for (const d of domains) {
        document.cookie = `${expire}; path=/${d ? `; domain=${d}` : ""}`;
      }
    }
  };
  remove();
  self.addEventListener("beforeunload", remove);
  document.addEventListener("visibilitychange", remove);
};

// Each generated data file pushes [scriptletName, argsByHost, excludedHosts]
// onto the queue just before this runtime executes.

function hostAncestors(hostname) {
  const out = [];
  const labels = hostname.split(".");
  for (let i = 0; i < labels.length; i++) out.push(labels.slice(i).join("."));
  return out;
}

const queue = self.__adwallQueue;
try { delete self.__adwallQueue; } catch {}

if (Array.isArray(queue)) {
  const ancestors = hostAncestors(location.hostname);
  for (const [name, argsByHost, excluded] of queue) {
    const scriptlet = SCRIPTLETS[name];
    if (!scriptlet || ancestors.some((h) => excluded[h])) continue;
    const seen = new Set();
    for (const host of ancestors) {
      for (const args of argsByHost[host] || []) {
        const key = natives.JSONstringify(args);
        if (seen.has(key)) continue;
        seen.add(key);
        try { scriptlet(...args); } catch {}
      }
    }
  }
}

})();
