"""Compile filter lists into everything AdWall loads at runtime.

Usage:  python tools/build.py [--offline]

Outputs (ads/trackers, always on):
  rules/lists.json         declarativeNetRequest rules (blocking, redirects, exceptions)
  rules/generic.css        element-hiding rules applied on every site
  rules/cosmetic.json      per-site CSS, generic exceptions, procedural filters
  scriptlets/runtime.js    scriptlet implementations (concatenated from scriptlets/src)
  scriptlets/gen/*.js      per-scriptlet host->arguments data
  scriptlets/index.json    which data file runs on which sites
Outputs (annoyances, off until switched on in options):
  rules/annoyances.json, rules/annoyances.css, rules/annoyances-cosmetic.json
Also: resources/*.gif|png transparent images, rules/build-info.json
"""
import ipaddress
import json
import struct
import sys
import time
import zlib
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from cosmetic import CosmeticCompiler  # noqa: E402
from lists import ANNOYANCE_LISTS, LISTS, load_all  # noqa: E402
from network import NetworkCompiler  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
TRUSTED_LISTS = {name for name in LISTS if name.startswith("ublock-")}


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, separators=(",", ":"), ensure_ascii=True), encoding="utf-8")


def build_network(lists, out_name, label):
    nc = NetworkCompiler()
    for lines in lists.values():
        nc.collect_badfilters(lines)
    for lines in lists.values():
        for line in lines:
            nc.add(line)
    rules = nc.emit()
    write_json(ROOT / "rules" / out_name, rules)
    actions = Counter(r["action"]["type"] for r in rules)
    domains = sum(len(r["condition"].get("requestDomains", [])) for r in rules if "urlFilter" not in r["condition"])
    print(f"{label} network: {len(rules)} rules ({dict(actions)}), {domains} grouped domains")
    return nc, {"rules": len(rules), "domains": domains}


def match_pattern(host):
    try:
        ipaddress.ip_address(host)
        return f"*://{host}/*"
    except ValueError:
        pass
    if "." not in host and host != "localhost":
        return None
    return f"*://*.{host}/*"


def build_cosmetic(lists, generichide_hosts, css_name, json_name, label, trusted_names):
    cc = CosmeticCompiler()
    for name, lines in lists.items():
        trusted = name in trusted_names
        for line in lines:
            if "#" in line:
                cc.add(line, trusted)
    cc.finalize()

    generic = sorted(cc.generic)
    (ROOT / "rules" / css_name).write_text(
        "\n".join(f"{sel}{{display:none!important}}" for sel in generic) + "\n", encoding="utf-8")

    write_json(ROOT / "rules" / json_name, {
        "specific": {h: "\n".join(sorted(rules)) for h, rules in sorted(cc.specific.items()) if rules},
        "genericExceptions": {h: sorted(s) for h, s in sorted(cc.generic_exceptions.items())},
        "generichide": sorted(generichide_hosts),
        "procedural": {h: [[base, [list(op) for op in ops]] for base, ops in sorted(specs)]
                       for h, specs in sorted(cc.procedural.items())},
    })
    print(f"{label} cosmetic: {len(generic)} generic, {len(cc.specific)} sites with specific CSS, "
          f"{len(cc.procedural)} sites with procedural filters")
    return cc, {"generic": len(generic), "sites": len(cc.specific)}


def build_scriptlets(cc):
    src = sorted((ROOT / "scriptlets" / "src").glob("*.js"))
    runtime = "// Generated by tools/build.py from scriptlets/src. Do not edit.\n(() => {\n"
    runtime += "\n".join(p.read_text(encoding="utf-8") for p in src) + "\n})();\n"
    (ROOT / "scriptlets" / "runtime.js").write_text(runtime, encoding="utf-8")

    gen = ROOT / "scriptlets" / "gen"
    gen.mkdir(parents=True, exist_ok=True)
    for old in gen.glob("*.js"):
        old.unlink()

    index, total = [], 0
    for name in sorted(cc.scriptlets):
        by_host = {h: args for h, args in sorted(cc.scriptlets[name].items()) if args}
        matches = sorted({m for m in map(match_pattern, by_host) if m})
        if not matches:
            continue
        excluded = cc.scriptlet_excluded.get(name, {})
        data = json.dumps([name, by_host, excluded], separators=(",", ":"), ensure_ascii=True)
        (gen / f"{name}.js").write_text(f"(self.__adwallQueue = self.__adwallQueue || []).push({data});\n", encoding="utf-8")
        index.append({"name": name, "file": f"scriptlets/gen/{name}.js", "matches": matches})
        total += sum(len(a) for a in by_host.values())
    write_json(ROOT / "scriptlets" / "index.json", index)
    print(f"scriptlets: {len(index)} kinds, {total} host filters")
    return {"kinds": len(index), "filters": total}


def png(width, height):
    raw = b"".join(b"\x00" + b"\x00\x00\x00\x00" * width for _ in range(height))
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))


def build_allow_ids():
    """Ids of allow rules, so the stats counter can tell blocks from exceptions."""
    out = {}
    for name in ("core", "lists", "annoyances"):
        path = ROOT / "rules" / f"{name}.json"
        if path.exists():
            rules = json.loads(path.read_text(encoding="utf-8"))
            out[name] = [r["id"] for r in rules if r["action"]["type"] in ("allow", "allowAllRequests")]
    write_json(ROOT / "rules" / "allow-ids.json", out)


def build_images():
    res = ROOT / "resources"
    res.mkdir(exist_ok=True)
    (res / "1x1.gif").write_bytes(
        b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04\x01\x00\x00\x00\x00"
        b",\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;")
    for w, h in ((2, 2), (3, 2), (32, 32)):
        (res / f"{w}x{h}.png").write_bytes(png(w, h))


def main():
    offline = "--offline" in sys.argv
    info = {"built": time.strftime("%Y-%m-%d %H:%M"), "lists": sorted(LISTS), "annoyanceLists": sorted(ANNOYANCE_LISTS)}

    lists = load_all(offline)
    nc, info["network"] = build_network(lists, "lists.json", "ads")
    cc, info["cosmetic"] = build_cosmetic(lists, nc.generichide_hosts, "generic.css", "cosmetic.json", "ads", TRUSTED_LISTS)
    info["scriptlets"] = build_scriptlets(cc)

    annoy = load_all(offline, ANNOYANCE_LISTS)
    anc, info["annoyanceNetwork"] = build_network(annoy, "annoyances.json", "annoyances")
    _, info["annoyanceCosmetic"] = build_cosmetic(
        annoy, anc.generichide_hosts, "annoyances.css", "annoyances-cosmetic.json", "annoyances",
        {n for n in ANNOYANCE_LISTS if n.startswith("ublock-")})

    build_allow_ids()
    build_images()
    write_json(ROOT / "rules" / "build-info.json", info)


if __name__ == "__main__":
    main()
